# Site settings
title: PET Computação UFPR
email: pet@inf.ufpr.br
description: > # this means to ignore newlines until "baseurl:"
  Site do PET Computação UFPR
baseurl: "/pet/" # the subpath of your site, e.g. /blog/
url: "https://petcomputacaoufpr.github.io" # the base hostname & protocol for your site
github_username:  PETComputacaoUFPR
safe: false
timezone: BR
enconding: utf-8

# Paginação
paginate: 5
paginate_path: "/page:num/"

# Build settings
markdown: kramdown

# Collections
collections:
  projetos:
    output: true

# Defaults
defaults:

    scope:
        path: ""
        type: "posts"
    values:
        layout: "post"

# Jekyll-Tagging
tag_page_layout: tag_page
tag_page_dir: tag
tag_permalink_style: pretty
