# Site settings
title: PET CSS
email: pet@inf.ufpr.br
description: > # this means to ignore newlines until "baseurl:"
  Biblioteca CSS feita pelo PET Computação UFPR para ser utilizada em projetos web
baseurl: "/site-pet/pet/" # the subpath of your site, e.g. /blog/
url: "http://petcomputacaoufpr.github.io/site-pet" # the base hostname & protocol for your site
github_username:  PETComputacaoUFPR

# Paginação
paginate: 5
paginate_path: "/pet/page:num/"

# Build settings
markdown: kramdown

# Defaults
defaults:
    
    scope:
        path: ""
        type: "posts"
    values:
        layout: "post"